#!/bin/sh
### BEGIN INIT INFO
# Provides:          <NAME>
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       <DESCRIPTION>
### END INIT INFO

APP_HOME=/opt/probe
CMD="nohup java -jar $APP_HOME/httpprobeServer.jar"
NAME=probeServer

PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log

start() {
  echo "Starting service..."
  if [ -f $PIDFILE ]; then
    PID=`cat $PIDFILE`
    if [ -z "`ps axf | grep $PID | grep -v grep`" ]; then
      echo "Process $PID dead but pidfile exists"
      rm -f $PIDFILE
      echo "Removed stun pidfile"
    else
      echo "Service already running"
      return 1
    fi
  fi
  PID=`$CMD > $LOGFILE 2>&1 & echo $!`
  if [ -z $PID ]; then
    echo "Failed to start the service"
  else
    echo $PID > $PIDFILE
    echo "Service started"
  fi
}

status() {
  if [ -f $PIDFILE ]; then
    PID=`cat $PIDFILE`
    if [ -z "`ps axf | grep $PID | grep -v grep`" ]; then
      echo "Process $PID dead but pidfile exists"
      rm -f $PIDFILE
      echo "Removed stun pidfile"
    else
      echo "Service is running"
    fi
  else
    echo "Service not running"
  fi
}

stop() {
  echo "Stopping service..."
  if [ -f $PIDFILE ]; then
    PID=`cat $PIDFILE`
    if [ -z "`ps axf | grep $PID | grep -v grep`" ]; then
      echo "Process $PID dead but pidfile exists"
      rm -f $PIDFILE
      echo "Removed stun pidfile"
    else
      kill -9 $PID
      rm -f $PIDFILE
      echo "Service stopped"
    fi
  else
    echo "Service not running"
  fi
}

uninstall() {
  echo "Not supported yet."
#  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
#  local SURE
#  read SURE
#  if [ "$SURE" = "yes" ]; then
#    stop
#    rm -f "$PIDFILE"
#    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
#    update-rc.d -f <NAME> remove
#    rm -fv "$0"
#  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
esac
